### ISSUE TITLE
Refactor role to remove multiple JDKs via a list of locations

### ISSUE THREAD

**Issue by frieder** [frieder/ansible-role-oraclejdk#12]
Currently it is only possible to remove multiple JDKs by using the same role over and over again. It could be useful to use a list of locations instead and only have an role occurence required.

### Current solution:
```
- role: frieder.oraclejdk
    oraclejdk_state: absent
    oraclejdk_home: /opt/java/jdk9.0.1
- role: frieder.oraclejdk
    oraclejdk_state: absent
    oraclejdk_home: /opt/java/jdk9.0.2
- role: frieder.oraclejdk
    oraclejdk_state: absent
    oraclejdk_home: /opt/java/jdk9.0.3
```

### New solution:
```
- role: frieder.oraclejdk
     oraclejdk_state: absent
     oraclejdk_home: 
     - /opt/java/jdk9.0.1
     - /opt/java/jdk9.0.2
     - /opt/java/jdk9.0.3
```
